apiVersion: 1

datasources:
  - name: SQLite Monitor
    type: frser-sqlite-datasource
    access: proxy
    url: file:/var/lib/grafana/monitor.db
    isDefault: true
    editable: true
    jsonData:
      path: /var/lib/grafana/monitor.db