apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zot-ingress
spec:
  rules:
  - host: zot.example.com  # Reemplaza esto con tu dominio o IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zot-service
            port:
              number: 5000
